import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, ClipboardList, ImagePlus, MapPinned, Plus, Route, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type TourStatus = "draft" | "ready" | "in_progress" | "completed" | "cancelled";
const toEpoch = (value: string) => (value ? new Date(value).getTime() : undefined);
const statusLabel: Record<TourStatus, string> = { draft: "Borrador", ready: "Preparada", in_progress: "En curso", completed: "Completada", cancelled: "Cancelada" };

function Card({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <section className="evox-card rounded-2xl p-4"><p className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-[#c9ff4a]">{icon}{title}</p><div className="mt-3">{children}</div></section>; }
function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <article className="evox-card rounded-2xl p-4"><p className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.12em] text-[#94a39b]"><span className="text-[#c9ff4a]">{icon}</span>{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-.045em]">{value}</p></article>; }

function nextStatuses(status: TourStatus): Exclude<TourStatus, "draft">[] {
  if (status === "draft") return ["ready", "cancelled"];
  if (status === "ready") return ["in_progress", "cancelled"];
  if (status === "in_progress") return ["completed", "cancelled"];
  return [];
}

export default function TourRun() {
  const { isAuthenticated, loading } = useAuth();
  const utils = trpc.useUtils();
  const dashboard = trpc.tourRun.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const [guide, setGuide] = useState({ name: "", phone: "", notes: "" });
  const [departure, setDeparture] = useState({ title: "", routeLabel: "", guideId: "", departureAt: "" });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [stop, setStop] = useState({ name: "", notes: "", scheduledAt: "" });
  const [participant, setParticipant] = useState({ displayName: "", partySize: "1" });
  const [evidence, setEvidence] = useState({ description: "", fileUrl: "" });
  const [incident, setIncident] = useState({ description: "", severity: "medium" as "low" | "medium" | "high" });
  const [transition, setTransition] = useState<{ nextStatus: Exclude<TourStatus, "draft">; confirmation: string; reason: string }>({ nextStatus: "ready", confirmation: "", reason: "" });
  const [accessEmail, setAccessEmail] = useState("");
  const [accessConfirmed, setAccessConfirmed] = useState(false);
  const refresh = () => void utils.tourRun.dashboard.invalidate();
  const error = { onError: (value: { message: string }) => toast.error(value.message) };
  const createGuide = trpc.tourRun.createGuide.useMutation({ ...error, onSuccess: () => { setGuide({ name: "", phone: "", notes: "" }); toast.success("Guía registrado"); refresh(); } });
  const createDeparture = trpc.tourRun.createDeparture.useMutation({ ...error, onSuccess: () => { setDeparture({ title: "", routeLabel: "", guideId: "", departureAt: "" }); toast.success("Salida creada como borrador"); refresh(); } });
  const addStop = trpc.tourRun.addStop.useMutation({ ...error, onSuccess: () => { setStop({ name: "", notes: "", scheduledAt: "" }); refresh(); } });
  const addParticipant = trpc.tourRun.addParticipant.useMutation({ ...error, onSuccess: () => { setParticipant({ displayName: "", partySize: "1" }); refresh(); } });
  const addEvidence = trpc.tourRun.addEvidence.useMutation({ ...error, onSuccess: () => { setEvidence({ description: "", fileUrl: "" }); refresh(); } });
  const addIncident = trpc.tourRun.addIncident.useMutation({ ...error, onSuccess: () => { setIncident({ description: "", severity: "medium" }); refresh(); } });
  const resolveIncident = trpc.tourRun.resolveIncident.useMutation({ ...error, onSuccess: refresh });
  const changeStatus = trpc.tourRun.transitionManually.useMutation({ ...error, onSuccess: (_, input) => { setTransition({ nextStatus: input.nextStatus, confirmation: "", reason: "" }); toast.success(`Salida ${statusLabel[input.nextStatus].toLowerCase()} mediante decisión humana`); refresh(); } });

  const guides = dashboard.data?.guides ?? [];
  const departures = dashboard.data?.departures ?? [];
  const selected = departures.find(row => row.id === selectedId) ?? departures.find(row => row.status !== "completed" && row.status !== "cancelled") ?? departures[0];
  const stops = useMemo(() => (dashboard.data?.stops ?? []).filter(row => row.departureId === selected?.id), [dashboard.data?.stops, selected?.id]);
  const participants = useMemo(() => (dashboard.data?.participants ?? []).filter(row => row.departureId === selected?.id), [dashboard.data?.participants, selected?.id]);
  const incidents = useMemo(() => (dashboard.data?.incidents ?? []).filter(row => row.departureId === selected?.id), [dashboard.data?.incidents, selected?.id]);
  const evidenceRows = useMemo(() => (dashboard.data?.evidence ?? []).filter(row => row.departureId === selected?.id), [dashboard.data?.evidence, selected?.id]);
  const openIncidents = (dashboard.data?.incidents ?? []).filter(row => row.status === "open").length;
  const availableTransitions = selected ? nextStatuses(selected.status as TourStatus) : [];
  const activeTransition = availableTransitions.includes(transition.nextStatus) ? transition.nextStatus : availableTransitions[0];
  const expectedConfirmation = activeTransition ? `CONFIRMAR ${activeTransition.toUpperCase()}` : "";

  if (loading || (isAuthenticated && dashboard.isLoading)) return <main className="evox-shell grid min-h-screen place-items-center text-sm text-[#94a39b]">Inicializando TourRun…</main>;
  if (!isAuthenticated) return <main className="evox-shell grid min-h-screen place-items-center p-5 text-[#f1f4ed]"><div className="evox-grid fixed inset-0 pointer-events-none opacity-40" /><section className="relative z-10 w-full max-w-sm rounded-3xl border border-white/10 bg-[#0b1711]/95 p-6 shadow-2xl shadow-black/30"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#c9ff4a] text-[#07120c]"><Route size={20} /></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[.18em] text-[#c9ff4a]">Acceso temporal</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.045em]">Evox TourRun</h1><p className="mt-3 text-sm leading-6 text-[#a8b8af]">Accede al tablero de salidas, guías, incidencias y evidencia. Las decisiones operativas seguirán requiriendo confirmación humana escrita.</p><form className="mt-6 grid gap-3" onSubmit={event => { event.preventDefault(); if (!accessConfirmed) return toast.error("Confirma que usarás una sesión de operador autorizada"); startLogin(); }}><label className="grid gap-1.5 text-xs font-medium text-[#d9e6dc]">Correo de trabajo<input required type="email" autoComplete="email" value={accessEmail} onChange={event => setAccessEmail(event.target.value)} className="evox-input text-sm" placeholder="operador@empresa.mx" /></label><label className="flex gap-2 rounded-xl border border-white/10 bg-white/[.025] p-3 text-xs leading-5 text-[#a8b8af]"><input className="mt-0.5 accent-[#c9ff4a]" type="checkbox" checked={accessConfirmed} onChange={event => setAccessConfirmed(event.target.checked)} /><span>Usaré una sesión de operador autorizada y revisaré manualmente cada decisión crítica.</span></label><button disabled={!accessEmail.trim() || !accessConfirmed} className="evox-button mt-1 px-4 py-3 text-sm">Continuar con acceso seguro</button></form><p className="mt-4 text-[11px] leading-5 text-[#718279]">Esta pantalla temporal no guarda el correo ni crea acceso local. La identidad y el aislamiento de datos se validan con la sesión segura del proyecto.</p><Link href="/" className="mt-5 inline-flex text-xs text-[#c9ff4a] underline-offset-4 hover:underline">Volver a PropertyOps</Link></section></main>;
  if (dashboard.isError) return <main className="evox-shell grid min-h-screen place-items-center p-6 text-[#f1f4ed]"><Card title="No cargamos TourRun" icon={<AlertTriangle size={16} />}><p className="text-sm text-[#94a39b]">No se modificó ninguna salida. Intenta cargar el tablero otra vez.</p><button onClick={() => dashboard.refetch()} className="evox-button mt-4 px-4 py-2 text-sm">Reintentar</button></Card></main>;

  return <main className="evox-shell min-h-screen text-[#f1f4ed]"><div className="evox-grid fixed inset-0 pointer-events-none opacity-40" />
    <header className="relative z-10 flex items-center justify-between border-b border-white/10 bg-[#07100d]/85 px-5 py-4 backdrop-blur-xl"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#c9ff4a] text-[#07120c]"><Route size={18} /></span><div><h1 className="font-semibold">Evox TourRun</h1><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#94a39b]">Mérida · operación de experiencias</p></div></div><Link href="/" className="evox-ghost inline-flex items-center gap-2 px-3 py-2 text-xs"><ArrowLeft size={14} />PropertyOps</Link></header>
    <div className="relative z-10 mx-auto grid max-w-7xl gap-5 p-5 lg:grid-cols-[300px_minmax(0,1fr)]">
      <aside className="space-y-5"><Card title="Registrar guía" icon={<UserRound size={15} />}><div className="grid gap-2"><input className="evox-input text-sm" value={guide.name} onChange={event => setGuide({ ...guide, name: event.target.value })} placeholder="Nombre del guía" /><input className="evox-input text-sm" value={guide.phone} onChange={event => setGuide({ ...guide, phone: event.target.value })} placeholder="Teléfono opcional" /><textarea className="evox-input min-h-20 text-sm" value={guide.notes} onChange={event => setGuide({ ...guide, notes: event.target.value })} placeholder="Notas opcionales" /><button disabled={!guide.name || createGuide.isPending} onClick={() => createGuide.mutate({ name: guide.name, phone: guide.phone || undefined, notes: guide.notes || undefined })} className="evox-button inline-flex items-center justify-center gap-2 px-3 py-2.5 text-xs"><Plus size={14} />Registrar guía</button></div></Card>
        <Card title="Nueva salida" icon={<CalendarClock size={15} />}><div className="grid gap-2"><input className="evox-input text-sm" value={departure.title} onChange={event => setDeparture({ ...departure, title: event.target.value })} placeholder="Ej. Cenotes del sur" /><input className="evox-input text-sm" value={departure.routeLabel} onChange={event => setDeparture({ ...departure, routeLabel: event.target.value })} placeholder="Ruta o punto de reunión" /><select className="evox-input text-sm" value={departure.guideId} onChange={event => setDeparture({ ...departure, guideId: event.target.value })}><option value="">Guía sin asignar por ahora</option>{guides.filter(row => row.status === "active").map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input type="datetime-local" className="evox-input text-sm" value={departure.departureAt} onChange={event => setDeparture({ ...departure, departureAt: event.target.value })} /><button disabled={!departure.title || !departure.routeLabel || createDeparture.isPending} onClick={() => createDeparture.mutate({ title: departure.title, routeLabel: departure.routeLabel, guideId: departure.guideId ? Number(departure.guideId) : undefined, departureAt: toEpoch(departure.departureAt) })} className="evox-ghost inline-flex items-center justify-center gap-2 px-3 py-2.5 text-xs"><Plus size={14} />Crear borrador</button></div></Card></aside>
      <section className="min-w-0 space-y-5"><section className="flex flex-col justify-between gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#c9ff4a]">Control de campo</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.055em]">La experiencia no se cierra sola.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#94a39b]">Guías, paradas, participantes, evidencias e incidencias en un flujo operativo auditable.</p></div><div className="max-w-xs rounded-xl border border-[#c9ff4a]/25 bg-[#c9ff4a]/[.055] px-3 py-2 text-xs leading-5 text-[#d9ff93]"><strong>Decisión humana.</strong> Preparar, iniciar, completar o cancelar una salida requiere confirmación escrita.</div></section>
        <div className="grid gap-3 sm:grid-cols-3"><Metric icon={<Route size={16} />} label="Salidas activas" value={String(departures.filter(row => row.status !== "completed" && row.status !== "cancelled").length)} /><Metric icon={<UsersRound size={16} />} label="Participantes" value={String((dashboard.data?.participants ?? []).reduce((total, row) => total + row.partySize, 0))} /><Metric icon={<AlertTriangle size={16} />} label="Incidencias abiertas" value={String(openIncidents)} /></div>
        <Card title="Salidas operativas" icon={<MapPinned size={15} />}><p className="mb-3 text-xs text-[#94a39b]">Elige una salida para registrar sus datos y tomar decisiones manuales.</p><div className="flex gap-2 overflow-x-auto pb-1">{departures.map(row => <button key={row.id} onClick={() => setSelectedId(row.id)} className={`min-w-48 rounded-xl border p-3 text-left transition ${selected?.id === row.id ? "border-[#c9ff4a] bg-[#c9ff4a]/[.06]" : "border-white/10 hover:bg-white/[.035]"}`}><span className="font-mono text-[10px] uppercase tracking-[.12em] text-[#c9ff4a]">{statusLabel[row.status as TourStatus]}</span><p className="mt-2 text-sm font-semibold">{row.title}</p><p className="mt-1 text-[11px] text-[#94a39b]">{row.routeLabel}</p></button>)}{!departures.length && <p className="rounded-xl border border-dashed border-white/10 px-4 py-6 text-sm text-[#94a39b]">Registra un guía y crea la primera salida como borrador.</p>}</div></Card>
        {selected && <div className="grid gap-5 xl:grid-cols-2"><Card title="Itinerario y participantes" icon={<ClipboardList size={15} />}><div className="grid gap-2">{stops.map(row => <div key={row.id} className="rounded-lg border border-white/10 p-3"><p className="text-sm font-semibold">{row.sequence}. {row.name}</p>{row.notes && <p className="mt-1 text-xs text-[#94a39b]">{row.notes}</p>}</div>)}<div className="grid gap-2 border-t border-white/10 pt-3"><input className="evox-input text-sm" value={stop.name} onChange={event => setStop({ ...stop, name: event.target.value })} placeholder="Nueva parada" /><input className="evox-input text-sm" value={stop.notes} onChange={event => setStop({ ...stop, notes: event.target.value })} placeholder="Nota opcional" /><input type="datetime-local" className="evox-input text-sm" value={stop.scheduledAt} onChange={event => setStop({ ...stop, scheduledAt: event.target.value })} /><button disabled={!stop.name || addStop.isPending} onClick={() => addStop.mutate({ departureId: selected.id, sequence: stops.length + 1, name: stop.name, notes: stop.notes || undefined, scheduledAt: toEpoch(stop.scheduledAt) })} className="evox-ghost px-3 py-2 text-xs">Añadir parada</button></div></div><div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold text-[#c9ff4a]">Participantes declarados</p><div className="mt-2 grid gap-2">{participants.map(row => <p key={row.id} className="rounded-lg border border-white/10 px-3 py-2 text-sm">{row.displayName}<span className="ml-2 text-xs text-[#94a39b]">· {row.partySize} persona(s)</span></p>)}<div className="grid grid-cols-[1fr_5rem_auto] gap-2"><input className="evox-input text-sm" value={participant.displayName} onChange={event => setParticipant({ ...participant, displayName: event.target.value })} placeholder="Nombre del grupo" /><input type="number" min="1" max="30" className="evox-input text-sm" value={participant.partySize} onChange={event => setParticipant({ ...participant, partySize: event.target.value })} /><button disabled={!participant.displayName || addParticipant.isPending} onClick={() => addParticipant.mutate({ departureId: selected.id, displayName: participant.displayName, partySize: Number(participant.partySize) || 1 })} className="evox-button px-3 text-xs">Agregar</button></div></div></div></Card>
          <div className="grid gap-5"><Card title="Evidencia e incidencias" icon={<ImagePlus size={15} />}><div className="grid gap-2">{evidenceRows.map(row => <a key={row.id} href={row.fileUrl || undefined} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 p-3 text-sm hover:bg-white/[.035]">{row.description}<span className="mt-1 block text-[10px] text-[#94a39b]">{row.fileUrl ? "Abrir URL" : "Nota sin enlace"}</span></a>)}<input className="evox-input text-sm" value={evidence.description} onChange={event => setEvidence({ ...evidence, description: event.target.value })} placeholder="Qué se observó" /><input type="url" className="evox-input text-sm" value={evidence.fileUrl} onChange={event => setEvidence({ ...evidence, fileUrl: event.target.value })} placeholder="URL opcional" /><button disabled={!evidence.description || addEvidence.isPending} onClick={() => addEvidence.mutate({ departureId: selected.id, description: evidence.description, fileUrl: evidence.fileUrl || undefined })} className="evox-ghost px-3 py-2 text-xs">Registrar evidencia</button></div><div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold text-[#c9ff4a]">Incidencias</p><div className="mt-2 grid gap-2">{incidents.map(row => <div key={row.id} className="rounded-lg border border-white/10 p-3"><p className="text-sm">{row.description}</p><div className="mt-2 flex items-center justify-between text-[10px] uppercase tracking-wider text-[#94a39b]"><span>{row.severity} · {row.status}</span>{row.status === "open" && <button onClick={() => resolveIncident.mutate({ incidentId: row.id })} className="text-[#c9ff4a]">Resolver</button>}</div></div>)}<input className="evox-input text-sm" value={incident.description} onChange={event => setIncident({ ...incident, description: event.target.value })} placeholder="Describe una incidencia" /><div className="grid grid-cols-[1fr_auto] gap-2"><select className="evox-input text-sm" value={incident.severity} onChange={event => setIncident({ ...incident, severity: event.target.value as typeof incident.severity })}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select><button disabled={!incident.description || addIncident.isPending} onClick={() => addIncident.mutate({ departureId: selected.id, ...incident })} className="evox-button px-3 text-xs">Registrar</button></div></div></div></Card>
            <Card title="Cambio de estado humano" icon={<ShieldCheck size={15} />}><p className="text-xs leading-5 text-[#94a39b]">Ninguna transición se ejecuta automáticamente. Las salidas preparadas necesitan guía y una parada; las completadas no pueden tener incidencias abiertas.</p>{activeTransition ? <div className="mt-3 grid gap-2"><select className="evox-input text-sm" value={activeTransition} onChange={event => setTransition({ ...transition, nextStatus: event.target.value as typeof transition.nextStatus, confirmation: "" })}>{availableTransitions.map(value => <option key={value} value={value}>{statusLabel[value]}</option>)}</select>{activeTransition === "cancelled" && <textarea className="evox-input min-h-20 text-sm" value={transition.reason} onChange={event => setTransition({ ...transition, reason: event.target.value })} placeholder="Motivo de cancelación" />}<input className="evox-input text-sm" value={transition.confirmation} onChange={event => setTransition({ ...transition, confirmation: event.target.value })} placeholder={`Escribe ${expectedConfirmation}`} /><button disabled={changeStatus.isPending || transition.confirmation.trim().toUpperCase() !== expectedConfirmation || (activeTransition === "cancelled" && transition.reason.trim().length < 5)} onClick={() => changeStatus.mutate({ departureId: selected.id, nextStatus: activeTransition, confirmation: transition.confirmation, reason: activeTransition === "cancelled" ? transition.reason : undefined })} className="evox-button px-3 py-2.5 text-xs">Confirmar decisión humana</button></div> : <p className="mt-3 rounded-lg border border-white/10 p-3 text-xs text-[#94a39b]">La salida está cerrada y no admite más cambios de estado.</p>}</Card></div></div>}
      </section>
    </div>
  </main>;
}
