import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { evoxModuleEvents, serviceRequests, serviceVendors, vendorQuotes } from "../drizzle/schema";
import { getDb } from "./db";
import { assertManualQuoteDecision, assertVendorOwned, QuoteStatus } from "./vendorRules";

async function database() { const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible"); return db as ReturnType<typeof drizzle>; }
async function event(ownerId: number, entityType: string, entityId: number, action: string, metadata?: Record<string, unknown>) { const db = await database(); await db.insert(evoxModuleEvents).values({ ownerId, actorId: ownerId, module: "vendor", entityType, entityId, action, metadata: metadata ? JSON.stringify(metadata) : null }); }
async function vendor(ownerId: number, vendorId: number) { const db = await database(); const row = (await db.select().from(serviceVendors).where(and(eq(serviceVendors.id, vendorId), eq(serviceVendors.ownerId, ownerId))).limit(1))[0]; if (!row) throw new Error("Proveedor no encontrado"); assertVendorOwned(row.ownerId, ownerId); return row; }
async function request(ownerId: number, requestId: number) { const db = await database(); const row = (await db.select().from(serviceRequests).where(and(eq(serviceRequests.id, requestId), eq(serviceRequests.ownerId, ownerId))).limit(1))[0]; if (!row) throw new Error("Solicitud no encontrada"); return row; }

export async function listVendorDashboard(ownerId: number) { const db = await database(); const [vendors, requests, quotes, events] = await Promise.all([db.select().from(serviceVendors).where(eq(serviceVendors.ownerId, ownerId)).orderBy(desc(serviceVendors.updatedAt)), db.select().from(serviceRequests).where(eq(serviceRequests.ownerId, ownerId)).orderBy(desc(serviceRequests.updatedAt)), db.select().from(vendorQuotes).where(eq(vendorQuotes.ownerId, ownerId)).orderBy(desc(vendorQuotes.createdAt)), db.select().from(evoxModuleEvents).where(and(eq(evoxModuleEvents.ownerId, ownerId), eq(evoxModuleEvents.module, "vendor"))).orderBy(desc(evoxModuleEvents.createdAt)).limit(30)]); return { vendors, requests, quotes, events }; }
export async function createVendor(ownerId: number, input: { name: string; category: string; phone?: string; contactEmail?: string; notes?: string }) { const db = await database(); const result = await db.insert(serviceVendors).values({ ownerId, name: input.name, category: input.category, phone: input.phone || null, contactEmail: input.contactEmail || null, notes: input.notes || null }); const row = await vendor(ownerId, Number(result[0].insertId)); await event(ownerId, "vendor", row.id, "vendor.created"); return row; }
export async function createServiceRequest(ownerId: number, input: { vendorId?: number; title: string; location: string; description: string }) { const db = await database(); if (input.vendorId) await vendor(ownerId, input.vendorId); const result = await db.insert(serviceRequests).values({ ownerId, vendorId: input.vendorId || null, title: input.title, location: input.location, description: input.description, status: input.vendorId ? "pending_visit" : "draft" }); const row = await request(ownerId, Number(result[0].insertId)); await event(ownerId, "request", row.id, "vendor.request_created", { vendorId: row.vendorId ?? undefined }); return row; }
export async function createVendorQuote(ownerId: number, input: { requestId: number; vendorId: number; description: string; amountCents: number; evidenceUrl?: string }) { const db = await database(); await request(ownerId, input.requestId); await vendor(ownerId, input.vendorId); const result = await db.insert(vendorQuotes).values({ ownerId, requestId: input.requestId, vendorId: input.vendorId, description: input.description, amountCents: input.amountCents, evidenceUrl: input.evidenceUrl || null }); await db.update(serviceRequests).set({ status: "quoted" }).where(and(eq(serviceRequests.id, input.requestId), eq(serviceRequests.ownerId, ownerId))); const quote = (await db.select().from(vendorQuotes).where(and(eq(vendorQuotes.id, Number(result[0].insertId)), eq(vendorQuotes.ownerId, ownerId))).limit(1))[0]; await event(ownerId, "quote", quote.id, "vendor.quote_created", { requestId: input.requestId }); return quote; }
export async function decideQuoteManually(ownerId: number, quoteId: number, decision: "accepted" | "rejected", confirmation: string) { const db = await database(); const quote = (await db.select().from(vendorQuotes).where(and(eq(vendorQuotes.id, quoteId), eq(vendorQuotes.ownerId, ownerId))).limit(1))[0]; if (!quote) throw new Error("Cotización no encontrada"); assertManualQuoteDecision({ currentStatus: quote.status as QuoteStatus, decision, confirmation }); await db.update(vendorQuotes).set({ status: decision, decidedByUserId: ownerId, decidedAt: new Date() }).where(and(eq(vendorQuotes.id, quoteId), eq(vendorQuotes.ownerId, ownerId), eq(vendorQuotes.status, "pending"))); if (decision === "accepted") await db.update(serviceRequests).set({ status: "scheduled" }).where(and(eq(serviceRequests.id, quote.requestId), eq(serviceRequests.ownerId, ownerId))); await event(ownerId, "quote", quoteId, "vendor.quote_manually_decided", { decision, decisionMode: "manual_ui" }); return (await db.select().from(vendorQuotes).where(and(eq(vendorQuotes.id, quoteId), eq(vendorQuotes.ownerId, ownerId))).limit(1))[0]; }
